# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:
# Linux
- bash: |
    sudo apt-get install -y libx11-dev libgl1-mesa-dev mesa-common-dev
    sudo apt-get remove -y gcc g++
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    sudo apt-get update
    sudo apt-get install -y gcc-8 g++-8
    curl -O -L https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz
    tar -C /opt -xf cmake-3.16.2-Linux-x86_64.tar.gz
    export PATH="/opt/cmake-3.16.2-Linux-x86_64/bin:${PATH}"

    mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: 'make'

- task: CopyFiles@2
  condition: eq( variables['Agent.OS'], 'Linux' )
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/agsconfig'
    contents: 'agsconfig'
    targetFolder: $(Build.ArtifactStagingDirectory)

# macOS
- bash: |
    curl -fLSs "https://github.com/Kitware/CMake/releases/download/v3.14.5/cmake-3.14.5-Darwin-x86_64.tar.gz" | bsdtar -f - -xvzC /Applications --strip-components 1
    mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: 'make'

- task: CopyFiles@2
  condition: eq( variables['Agent.OS'], 'Darwin' )
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/build/'
    contents: 'agsconfig'
    targetFolder: $(Build.ArtifactStagingDirectory)

# Windows
- task: CMake@1
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  inputs:
    cmakeArgs: .. -DCMAKE_BUILD_TYPE=Release 

- task: CopyFiles@2
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/build/'
    contents: 'agsconfig.exe'
    targetFolder: $(Build.ArtifactStagingDirectory)

- bash: |
    echo "##vso[task.setvariable variable=tagname]$(git describe --tags $(git rev-list --tags --max-count=1))"
# Upload to Github Release
- task: GithubRelease@0
  displayName: 'Create GitHub Release'
  inputs:
    tagSource: 'auto'
    tag: $(tagname)
    assetUploadMode: 'replace'
    action: 'edit'
    gitHubConnection: agsconfig
    repositoryName: ericoporto/agsconfig
    assets: |
         $(Build.ArtifactStagingDirectory)/agsconfig.exe
         $(Build.ArtifactStagingDirectory)/agsconfig
         $(Build.ArtifactStagingDirectory)/*.dylib
